#!/bin/bash
find . -lname '/usr/share/icons/El General/*' -printf '%p\0%l\0' |
  awk -vRS='\0' '
    {
      getline target
      sub("^/usr/share/icons/El General", "/usr/share/icons/ElGeneral", target)
      printf("%s\0%s\0", target, $0)
    }' |
  xargs -r0n2 ln -sfT
